apiVersion: apps/v1
kind: Deployment
metadata:
  name: API
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vshvadchak/test:latest
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: gogs
spec:
  ports:
  - name: port-2
    port: 5000
    nodePort: 30005
    protocol: TCP
  selector:
     app: api
  type: LoadBalancer
status:
  loadBalancer: {}
---